import type { NextPage } from 'next';
import Head from 'next/head';
import PageContentWrap from '../../../components/generic/PageContentWrap';
import Flex from '../../../components/generic/Flex';
import Footer from '../../../components/Footer';
import PageWithFooter from '../../../components/generic/PageWithFooter';
import Banner from '../../../components/Banner';
import PageTitle from '../../../components/PageTitle';
import PageIntro from '../../../components/PageIntro';
import tools from '../../../data/tools/list';
import Link from 'next/link';
import { useRouter } from 'next/router';
import { useEffect, useState } from 'react';
import CodeBox from '../../../components/generic/CodeBox';
import DetachedHoverEffect from '../../../components/generic/DetachedHoverEffect';
import s from './[slug].module.css';
import ContentSlider from '../../../components/generic/ContentSlider';

const ToolsReactLibrary: NextPage = () => {
  const router = useRouter();

  const [currentTool, setCurrentTool] = useState();

  useEffect(() => {
    const tool = tools.find((tool) => tool.slug === router.query.slug);

    if (!tool) {
      return;
    }

    setCurrentTool(tool);
  }, [router]);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <PageWithFooter>
        <main style={{ background: '#ECF4FA' }}>
          <Banner />
          <PageContentWrap>
            <div style={{ marginBottom: 96 }}>
              <div style={{ textAlign: 'center', marginTop: 64 }}>
                <PageTitle>React Behavioural UI Component Library</PageTitle>
                <PageIntro>
                  A collection of components that provide behaviours and
                  utilities to your visual UI components.
                </PageIntro>
              </div>
            </div>
            <Flex style={{ margin: 'auto', flexWrap: 'wrap' }}>
              {tools.map((tool) => (
                <Link
                  key={tool.slug}
                  href={tool.slug}
                  scroll={false}
                  passHref={true}
                  style={{
                    margin: '24px',
                  }}
                >
                  <DetachedHoverEffect
                    className={`${s.hover} ${
                      currentTool &&
                      tool.slug === currentTool.slug &&
                      s.hoverSelect
                    }`}
                  >
                    <span
                      style={{
                        display: 'block',
                        paddingLeft: '16px',
                        paddingRight: '16px',
                        paddingTop: '8px',
                        paddingBottom: '8px',
                      }}
                    >
                      {tool.title}
                    </span>
                  </DetachedHoverEffect>
                </Link>
              ))}
            </Flex>
            <p
              style={{
                maxWidth: 700,
                marginLeft: 'auto',
                marginRight: 'auto',
                marginTop: '48px',
                marginBottom: '48px',
              }}
            >
              {currentTool ? currentTool.description : 'Component not found.'}
            </p>

            <div style={{ marginBottom: 96 }}>
              {currentTool &&
                currentTool.content.map((example, index) => (
                  <Flex
                    key={index}
                    style={{
                      alignItems: 'stretch',
                      marginBottom: 48,
                    }}
                  >
                    <div
                      style={{
                        width: '50%',
                        marginRight: 8,
                        flexGrow: 0,
                        flexShrink: 0,
                      }}
                    >
                      {example.exampleMarkDown && (
                        <CodeBox
                          code={example.exampleMarkDown}
                          style={{ height: '100%' }}
                        />
                      )}
                    </div>

                    <div
                      style={{
                        marginLeft: 8,
                        width: '50%',
                        border: '2px solid #262C35',
                        borderRadius: '6px',
                        padding: '16px',
                        flexGrow: 0,
                        flexShrink: 0,
                      }}
                    >
                      <example.example />
                    </div>
                  </Flex>
                ))}
            </div>
          </PageContentWrap>
        </main>
        <Footer />
      </PageWithFooter>
    </>
  );
};

export default ToolsReactLibrary;
