import type { NextPage } from 'next';
import Head from 'next/head';
import PageContentWrap from '../../components/generic/PageContentWrap';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import {
  faAws,
  faCss3,
  faGit,
  faGithub,
  faHtml5,
  faJs,
  faJsSquare,
  faNode,
  faNodeJs,
  faReact,
  faShopify,
} from '@fortawesome/free-brands-svg-icons';
import Banner from '../../components/Banner';
import ProjectCard from '../../components/ProjectCard';
import ProjectCardWide from '../../components/ProjectCardWide';
import PageTitle from '../../components/PageTitle';
import PageIntro from '../../components/PageIntro';
import projects from '../../data/projects';
import s from './index.module.css';
import Heading from '../../components/Heading';
import Image from 'next/image';
import DetachedHoverEffect from '../../components/generic/DetachedHoverEffect';
import Link from 'next/link';
import Masonry from 'react-masonry-css';
import ReadingListItem from '../../components/ReadingListItem';

const ReadingList: NextPage = () => {
  const readingList = [
    {
      title: 'On Opening Essays, Conference Talks, and Jam Jars',
      description:
        'A wonderful explanation on generative technologies made extremely simple.',
      url: 'https://maggieappleton.com/openings',
      source: 'Maggie Appleton',
      icon: 'maggie-appleton_icon.png',
      type: 'Article',
      // image: '/images/projects/binder/binder_image_01.jpg',
      topics: ['AI', 'Databasing'],
      timeAdded: new Date(),
    },
    {
      title: 'Interface In Game',
      description:
        'A collection of user interfaces from over 350 games to explore and inspire.',
      url: 'https://interfaceingame.com/',
      source: 'Interface In Game',
      icon: 'interface-in-game_icon.png',
      type: 'Link',
      topics: ['Design', 'Game Dev'],
      timeAdded: new Date(),
    },
    {
      title: 'Hexagonal Grids from Red Blob Games',
      description:
        'A unbelievable deep dive into the maths involved with working with a hexagonal grid system with interactive diagrams.',
      url: 'https://www.redblobgames.com/grids/hexagons/',
      source: 'Red Blob Games',
      icon: 'red-blob-games_icon.png',
      type: 'Article',
      topics: ['Math', 'Game Dev'],
      timeAdded: new Date(),
    },
    {
      title: 'On Opening Essays, Conference Talks, and Jam Jars',
      description:
        'A wonderful explanation on generative technologies made extremely simple.',
      url: 'https://maggieappleton.com/openings2322',
      source: 'Maggie Appleton',
      icon: 'maggie-appleton_icon.png',
      type: 'Article',
      topics: ['AI', 'Databasing'],
      timeAdded: new Date(),
    },
    {
      title: 'On Opening Essays, Conference Talks, and Jam Jars',
      description:
        'A wonderful explanation on generative technologies made extremely simple.',
      url: 'https://maggieappleton.com/openings222',
      source: 'Maggie Appleton',
      icon: 'maggie-appleton_icon.png',
      type: 'Article',
      topics: ['AI', 'Databasing'],
      timeAdded: new Date(),
    },
    {
      title: 'Interface In Game',
      description:
        'A collection of user interfaces from over 350 games to explore and inspire.',
      url: 'https://interfaceingame.com/2223',
      source: 'Interface In Game',
      icon: 'interface-in-game_icon.png',
      type: 'Link',
      topics: ['Design', 'Game Dev'],
      timeAdded: new Date(),
    },
    {
      title: 'Hexagonal Grids from Red Blob Games',
      description:
        'A unbelievable deep dive into the maths involved with working with a hexagonal grid system with interactive diagrams.',
      url: 'https://www.redblobgames.com/grids/hexagons/333',
      source: 'Red Blob Games',
      icon: 'red-blob-games_icon.png',
      type: 'Article',
      topics: ['Math', 'Game Dev'],
      timeAdded: new Date(),
    },
    {
      title: 'On Opening Essays, Conference Talks, and Jam Jars',
      description:
        'A wonderful explanation on generative technologies made extremely simple.',
      url: 'https://maggieappleton.com/openings333',
      source: 'Maggie Appleton',
      icon: 'maggie-appleton_icon.png',
      type: 'Article',
      topics: ['AI', 'Databasing'],
      timeAdded: new Date(),
    },
  ];
  const columnBreakpoints = {
    default: 3,
    1100: 2,
    700: 1,
  };
  return (
    <>
      <Head>
        <title>Reading List | Phillip Miles React Portfolio</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <Banner />
      <PageContentWrap>
        <main
          className={s.main}
          style={{
            marginBottom: 96,
            color: '#343435',
          }}
        >
          <div
            style={{
              marginTop: 64,
              marginBottom: 96,
            }}
          >
            <h1 style={{}}>Reading list</h1>
            <h2
              style={{
                fontSize: '26px',
                fontFamily: 'metropolis',
                fontWeight: '400',
                maxWidth: '700px',
              }}
            >
              {/* Things I've found on the web that I recommend. */}
              Interesting things I found on the web that made my dopamine
              receptors go <i>woosh!</i> <b>bam!</b> <u>zap!</u>
            </h2>
          </div>
          {/* <div className={s.grid}> */}
          <Masonry
            breakpointCols={columnBreakpoints}
            className={s.masonryGrid}
            columnClassName={s.masonryGridColumn}
          >
            {readingList.map((item) => (
              <DetachedHoverEffect key={item.url} className={s.itemHoverEffect}>
                <ReadingListItem
                  url={item.url}
                  title={item.title}
                  description={item.description}
                  source={item.source}
                  icon={item.icon}
                  type={item.type}
                  image={item.image}
                />
              </DetachedHoverEffect>
            ))}
          </Masonry>
          {/* <div>
              <h3>Links</h3>
              <p>Interface In Game</p>
              <p>https://interfaceingame.com/</p>
            </div> */}
          {/* </div> */}
        </main>
      </PageContentWrap>
    </>
  );
};

export default ReadingList;
