import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import PageContentWrap from '../../components/generic/PageContentWrap';
import Nav from '../../components/Nav';
import Button from '../../components/generic/Button';
import Link from 'next/link';
import DevTools from '../../components/DevTools';
import Flex from '../../components/generic/Flex';
import Footer from '../../components/Footer';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import {
  faAws,
  faCss3,
  faGit,
  faGithub,
  faHtml5,
  faJs,
  faJsSquare,
  faNode,
  faNodeJs,
  faReact,
  faShopify,
} from '@fortawesome/free-brands-svg-icons';
import PageWithFooter from '../../components/generic/PageWithFooter';
import Banner from '../../components/Banner';
import ProjectCard from '../../components/ProjectCard';
import PageTitle from '../../components/PageTitle';
import PageIntro from '../../components/PageIntro';

import s from '../../styles/Project.module.css';

import projects from '../../data/projects';

import { useRouter } from 'next/router';
import { useEffect, useMemo, useState } from 'react';

const Projects: NextPage = (props) => {
  const router = useRouter();
  const [project, setProject] = useState();
  const [content, setContent] = useState('');

  // Setup facebook share
  // useEffect(() => {
  //   (function (d, s, id) {
  //     var js,
  //       fjs = d.getElementsByTagName(s)[0];
  //     if (d.getElementById(id)) return;
  //     js = d.createElement(s);
  //     js.id = id;
  //     js.src = 'https://connect.facebook.net/en_US/sdk.js#xfbml=1&version=v3.0';
  //     fjs.parentNode.insertBefore(js, fjs);
  //   })(document, 'script', 'facebook-jssdk');
  // }, []);

  useEffect(() => {
    if (router.isReady) {
      const project = projects.find(
        (project) => project.slug === router.query.slug
      );
      if (!project) return;

      setProject(project);

      // const content = project.content({});

      // if (!content) return;
      // setContent(() => content);
    }
  }, [router.isReady, router.query.slug]);
  // const project = router.isReady
  //   ? projects.find((project) => project.slug === router.query.slug)
  //   : {};

  // }

  // useEffect(() => {
  //   if (router.isReady) {
  //     project = projects.find((project) => project.slug === router.query.slug);
  //   }
  // }, [router.isReady]);
  // const project = projects.find(
  //   (project) => project.slug === router.query.slug
  // );

  // console.log('sdfsdf', router.isReady, project);

  // if (!project) {
  //   return;
  // }

  // const project =
  // const content = project.content({});

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta
          property="og:url"
          content={`https://www.phillipmiles.com/projects/${router.query.slug}`}
        />
        <meta property="og:type" content="website" />
        <meta property="og:title" content="Your Website Title" />
        <meta property="og:description" content="Your description" />
        <meta
          property="og:image"
          content="https://www.your-domain.com/path/image.jpg"
          key={`./images/projects/${router.query.slug}/${router.query.slug}_thumbnail_01.jpg`}
        />
      </Head>

      <Banner />
      <PageContentWrap>
        <div style={{ marginBottom: 96 }}>
          {router.isReady && project && (
            <>
              <div
                style={{
                  textAlign: 'center',
                  marginTop: 64,
                  marginBottom: 96,
                }}
              >
                <p style={{ marginBottom: 30 }}>{project.year}</p>
                <PageTitle>{project.name}</PageTitle>
                <PageIntro>{project.intro}</PageIntro>
                {/* <div
                    style={{
                      position: 'relative',
                      width: '100%',
                      height: 512,
                      marginBottom: 96,
                    }}
                  >
                    <Image
                      src={project.bannerSrc}
                      alt={project.bannerAlt}
                      fill={true}
                      style={{ objectFit: 'cover' }}
                    />
                  </div> */}
              </div>
              <div className={s.content}>{project.content}</div>
              <Flex
                style={{
                  justifyContent: 'center',
                  alignItems: 'center',
                  marginTop: '60px',
                }}
              >
                <p style={{ margin: '16px' }}>Share on:</p>
                <a
                  rel="canonical"
                  data-size="large"
                  className={`twitter-share-button ${s.shareButton}`}
                  href={`https://twitter.com/intent/tweet?text=www.phillipmiles.com/projects/${router.query.slug}`}
                >
                  <Image
                    src={'/images/companies/icons/x-icon.svg'}
                    width={32}
                    height={32}
                    alt="Share on X"
                    style={{ margin: 8, color: 'black' }}
                  />
                </a>

                <div id="fb-root"></div>
                <script
                  async
                  defer
                  crossOrigin="anonymous"
                  src="https://connect.facebook.net/en_US/sdk.js#xfbml=1&version=v18.0"
                  nonce="QgmLflDB"
                ></script>

                <div
                  className={`fb-share-button ${s.shareButton}`}
                  data-href="https://www.phillipmiles.com"
                  data-layout=""
                  data-size=""
                >
                  <a
                    target="_blank"
                    href={`https://www.facebook.com/sharer/sharer.php?u=https%3A%2F%2Fwww.phillipmiles.com/projects/${router.query.slug}%2F&amp;src=sdkpreparse`}
                    className="fb-xfbml-parse-ignore"
                  >
                    <Image
                      src={'/images/companies/icons/facebook-icon.svg'}
                      width={32}
                      height={32}
                      alt="Share on Facebook"
                      style={{ margin: 8, color: 'black' }}
                    />
                  </a>
                </div>
              </Flex>
            </>
          )}
        </div>
      </PageContentWrap>
    </>
  );
};

export default Projects;
