import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import PageContentWrap from '../../components/generic/PageContentWrap';
import Nav from '../../components/Nav';
import Button from '../../components/generic/Button';
import Link from 'next/link';
import DevTools from '../../components/DevTools';
import Flex from '../../components/generic/Flex';
import Footer from '../../components/Footer';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import {
  faAws,
  faCss3,
  faGit,
  faGithub,
  faHtml5,
  faJs,
  faJsSquare,
  faNode,
  faNodeJs,
  faReact,
  faShopify,
} from '@fortawesome/free-brands-svg-icons';
import PageWithFooter from '../../components/generic/PageWithFooter';
import Banner from '../../components/Banner';
import ProjectCard from '../../components/ProjectCard';
import PageTitle from '../../components/PageTitle';
import PageIntro from '../../components/PageIntro';

import styles from '../../styles/Project.module.css';

import projects from '../../data/projects';

import { useRouter } from 'next/router';
import { useEffect, useMemo, useState } from 'react';

const Projects: NextPage = (props) => {
  const router = useRouter();
  const [project, setProject] = useState();
  const [content, setContent] = useState('');

  useEffect(() => {
    if (router.isReady) {
      const project = projects.find(
        (project) => project.slug === router.query.slug
      );
      if (!project) return;

      setProject(project);

      // const content = project.content({});

      // if (!content) return;
      // setContent(() => content);
    }
  }, [router.isReady, router.query.slug]);
  // const project = router.isReady
  //   ? projects.find((project) => project.slug === router.query.slug)
  //   : {};

  // }

  // useEffect(() => {
  //   if (router.isReady) {
  //     project = projects.find((project) => project.slug === router.query.slug);
  //   }
  // }, [router.isReady]);
  // const project = projects.find(
  //   (project) => project.slug === router.query.slug
  // );

  // console.log('sdfsdf', router.isReady, project);

  // if (!project) {
  //   return;
  // }

  // const project =
  // const content = project.content({});

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <Banner />
      <PageContentWrap>
        <div style={{ marginBottom: 96 }}>
          {router.isReady && project && (
            <div
              style={{
                textAlign: 'center',
                marginTop: 64,
                marginBottom: 96,
              }}
            >
              <PageTitle>{project.name}</PageTitle>
              <PageIntro>{project.intro}</PageIntro>
              <p style={{ marginBottom: 96 }}>{project.year}</p>
              {/* <div
                    style={{
                      position: 'relative',
                      width: '100%',
                      height: 512,
                      marginBottom: 96,
                    }}
                  >
                    <Image
                      src={project.bannerSrc}
                      alt={project.bannerAlt}
                      fill={true}
                      style={{ objectFit: 'cover' }}
                    />
                  </div> */}
              <div className={styles.content}>{project.content}</div>
            </div>
          )}
        </div>
      </PageContentWrap>
    </>
  );
};

export default Projects;
