import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';

import PageContentWrap from '../../components/generic/PageContentWrap';
import Nav from '../../components/Nav';
import Button from '../../components/generic/Button';
import Link from 'next/link';
import DevTools from '../../components/DevTools';
import Flex from '../../components/generic/Flex';
import Footer from '../../components/Footer';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import {
  faAws,
  faCss3,
  faGit,
  faGithub,
  faHtml5,
  faJs,
  faJsSquare,
  faNode,
  faNodeJs,
  faReact,
  faShopify,
} from '@fortawesome/free-brands-svg-icons';
import PageWithFooter from '../../components/generic/PageWithFooter';
import Banner from '../../components/Banner';
import ProjectCard from '../../components/ProjectCard';
import PageTitle from '../../components/PageTitle';
import PageIntro from '../../components/PageIntro';
import projects from '../../data/projects';
import s from './projects.module.css';

const Projects: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <Banner />
      <PageContentWrap>
        <div style={{ marginBottom: 96 }}>
          <div style={{ textAlign: 'center', marginTop: 64, marginBottom: 96 }}>
            <PageTitle>Projects</PageTitle>
            <PageIntro>
              A sample of projects I have worked on both personal and
              professional.
            </PageIntro>
          </div>
          {projects.map((project) => (
            <ProjectCard
              key={project.slug}
              slug={project.slug}
              title={project.name}
              description={project.description}
              url={`/projects/${project.slug}`}
              srcThumb={project.thumbnail}
              className={s.projectCard}
            />
          ))}
          {/* <ProjectCard
                title="Verso Learning App"
                description={
                  'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean eros velit, sollicitudin vel gravida sit amet, gravida eget sapien. Proin tellus lorem, rhoncus eu pharetra non, dapibus a nisl. Fusce aliquam nisi ut nunc suscipit sollicitudin.'
                }
                url="/"
                srcThumb="/images/versohome.png"
                style={{ marginBottom: 64 }}
              />
              <ProjectCard
                title="Thought Stream Mobile App"
                description={
                  'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean eros velit, sollicitudin vel gravida sit amet, gravida eget sapien. Proin tellus lorem, rhoncus eu pharetra non, dapibus a nisl. Fusce aliquam nisi ut nunc suscipit sollicitudin.'
                }
                url="/"
                srcThumb="/projects-thumb.png"
                style={{ marginBottom: 64 }}
              />
              <ProjectCard
                title="Test"
                description={
                  'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean eros velit, sollicitudin vel gravida sit amet, gravida eget sapien. Proin tellus lorem, rhoncus eu pharetra non, dapibus a nisl. Fusce aliquam nisi ut nunc suscipit sollicitudin.'
                }
                url="/"
                srcThumb="/images/cpa_screen_ipad.jpeg"
                style={{ marginBottom: 64 }}
              />
              <ProjectCard
                title="Test"
                description={
                  'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean eros velit, sollicitudin vel gravida sit amet, gravida eget sapien. Proin tellus lorem, rhoncus eu pharetra non, dapibus a nisl. Fusce aliquam nisi ut nunc suscipit sollicitudin.'
                }
                url="/"
                srcThumb="/images/gametalk_composite.jpeg"
                style={{ marginBottom: 64 }}
              /> */}
        </div>
      </PageContentWrap>
    </>
  );
};

export default Projects;
