import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';

import PageContentWrap from '../../components/generic/PageContentWrap';
import Nav from '../../components/Nav';
import Button from '../../components/generic/Button';
import Link from 'next/link';
import DevTools from '../../components/DevTools';
import Flex from '../../components/generic/Flex';
import Footer from '../../components/Footer';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import {
  faAws,
  faCss3,
  faGit,
  faGithub,
  faHtml5,
  faJs,
  faJsSquare,
  faNode,
  faNodeJs,
  faReact,
  faShopify,
} from '@fortawesome/free-brands-svg-icons';
import PageWithFooter from '../../components/generic/PageWithFooter';
import Banner from '../../components/Banner';
import ProjectCard from '../../components/ProjectCard';
import PageTitle from '../../components/PageTitle';
import PageIntro from '../../components/PageIntro';
import projects from '../../data/projects';
import s from './projects.module.css';
import ProjectCardImage from '../../components/ProjectCardImage';
import ProjectCardBody from '../../components/ProjectCardBody';
import ProjectCardTitle from '../../components/ProjectCardTitle';
import ProjectCardDescription from '../../components/ProjectCardDescription';

const Projects: NextPage = () => {
  return (
    <>
      <Head>
        <title>Projects | Phillip Miles</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <Banner />
      <PageContentWrap>
        <div style={{ marginBottom: 96 }}>
          <div style={{ textAlign: 'center', marginTop: 64, marginBottom: 96 }}>
            <PageTitle>Projects</PageTitle>
            <PageIntro>
              A sample of projects I have worked on both personally and
              professionally.
            </PageIntro>
          </div>

          <Flex
            className={s.projectCard}
            style={{
              background: 'white',
              borderRadius: '6px',
              overflow: 'hidden',
              minHeight: '500px',
            }}
          >
            <ProjectCardBody
              url={`/projects/${projects[0].slug}`}
              slug={projects[0].slug}
              title={projects[0].name}
              description={projects[0].description}
            >
              <ProjectCardTitle className={'h3'}>
                {projects[0].name}
              </ProjectCardTitle>
              <ProjectCardDescription lines={6}>
                {projects[1].description}
              </ProjectCardDescription>
            </ProjectCardBody>
            <ProjectCardImage
              slug={projects[0].slug}
              url={`/projects/${projects[0].slug}`}
              src={projects[0].thumbnail}
            />
          </Flex>

          <Flex style={{ gap: '24px' }}>
            <Flex
              className={s.projectCard}
              style={{
                background: 'white',
                borderRadius: '6px',
                overflow: 'hidden',
                minHeight: '400px',
                flexDirection: 'column',
              }}
            >
              <ProjectCardImage
                slug={projects[1].slug}
                url={`/projects/${projects[1].slug}`}
                src={projects[1].thumbnail}
                style={{ minHeight: '240px' }}
              />
              <ProjectCardBody
                url={`/projects/${projects[1].slug}`}
                slug={projects[1].slug}
                style={{ width: '100%', padding: '32px' }}
              >
                <ProjectCardTitle className={'h4'}>
                  {projects[0].name}
                </ProjectCardTitle>
                <ProjectCardDescription lines={4}>
                  {projects[1].description}
                </ProjectCardDescription>
              </ProjectCardBody>
            </Flex>
            <Flex
              className={s.projectCard}
              style={{
                background: 'white',
                borderRadius: '6px',
                overflow: 'hidden',
                minHeight: '400px',
                flexDirection: 'column',
              }}
            >
              <ProjectCardImage
                slug={projects[2].slug}
                url={`/projects/${projects[2].slug}`}
                src={projects[2].thumbnail}
                style={{ minHeight: '240px' }}
              />
              <ProjectCardBody
                url={`/projects/${projects[2].slug}`}
                slug={projects[2].slug}
                title={projects[2].name}
                description={projects[2].description}
                style={{ width: '100%', padding: '32px' }}
              >
                <ProjectCardTitle className={'h4'}>
                  {projects[0].name}
                </ProjectCardTitle>
                <ProjectCardDescription lines={4}>
                  {projects[1].description}
                </ProjectCardDescription>
              </ProjectCardBody>
            </Flex>
            <Flex
              className={s.projectCard}
              style={{
                background: 'white',
                borderRadius: '6px',
                overflow: 'hidden',
                minHeight: '400px',
                flexDirection: 'column',
              }}
            >
              <ProjectCardImage
                slug={projects[3].slug}
                url={`/projects/${projects[3].slug}`}
                src={projects[3].thumbnail}
                style={{ minHeight: '240px' }}
              />
              <ProjectCardBody
                url={`/projects/${projects[3].slug}`}
                slug={projects[3].slug}
                title={projects[3].name}
                description={projects[3].description}
                style={{ width: '100%', padding: '32px' }}
              >
                <ProjectCardTitle className={'h4'}>
                  {projects[0].name}
                </ProjectCardTitle>
                <ProjectCardDescription lines={4}>
                  {projects[1].description}
                </ProjectCardDescription>
              </ProjectCardBody>
            </Flex>
          </Flex>

          <Flex
            className={s.projectCard}
            style={{
              background: 'white',
              borderRadius: '6px',
              overflow: 'hidden',
              minHeight: '500px',
            }}
          >
            <ProjectCardBody
              url={`/projects/${projects[0].slug}`}
              slug={projects[0].slug}
              title={projects[0].name}
              description={projects[0].description}
            >
              <ProjectCardTitle className={'h3'}>
                {projects[0].name}
              </ProjectCardTitle>
              <ProjectCardDescription lines={6}>
                {projects[1].description}
              </ProjectCardDescription>
            </ProjectCardBody>
            <ProjectCardImage
              slug={projects[0].slug}
              url={`/projects/${projects[0].slug}`}
              src={projects[0].thumbnail}
            />
          </Flex>

          <Flex style={{ gap: '24px', marginBottom: '24px' }}>
            <div style={{ width: '60%' }}>
              <Flex
                style={{
                  background: 'white',
                  borderRadius: '6px',
                  overflow: 'hidden',
                  minHeight: '300px',
                  flexDirection: 'row',
                  maxHeight: '200px',
                  marginBottom: '24px',
                }}
              >
                <ProjectCardImage
                  slug={projects[6].slug}
                  url={`/projects/${projects[6].slug}`}
                  src={projects[6].thumbnail}
                  style={{ minWidth: '300px' }}
                />
                <ProjectCardBody
                  url={`/projects/${projects[6].slug}`}
                  slug={projects[6].slug}
                  title={projects[6].name}
                  // description={projects[6].description}
                  style={{ width: '100%' }}
                >
                  <ProjectCardTitle className={'h4'}>
                    {projects[6].name}
                  </ProjectCardTitle>
                  <ProjectCardDescription>
                    {projects[6].description}
                  </ProjectCardDescription>
                </ProjectCardBody>
              </Flex>
              <Flex
                style={{
                  background: 'white',
                  borderRadius: '6px',
                  overflow: 'hidden',
                  minHeight: '300px',
                  flexDirection: 'row',
                  maxHeight: '200px',
                }}
              >
                <ProjectCardImage
                  slug={projects[4].slug}
                  url={`/projects/${projects[6].slug}`}
                  src={projects[4].thumbnail}
                  style={{ minWidth: '300px' }}
                />
                <ProjectCardBody
                  url={`/projects/${projects[4].slug}`}
                  slug={projects[4].slug}
                  title={projects[4].name}
                  // description={projects[6].description}
                  style={{ width: '100%' }}
                >
                  <ProjectCardTitle className={'h4'}>
                    {projects[4].name}
                  </ProjectCardTitle>
                  <ProjectCardDescription>
                    {projects[4].description}
                  </ProjectCardDescription>
                </ProjectCardBody>
              </Flex>
            </div>
            <Flex
              style={{
                background: 'white',
                borderRadius: '6px',
                overflow: 'hidden',
                // minHeight: '400px',
                flexGrow: 1,
                flexDirection: 'column',
                width: '40%',
                // maxHeight: '600px',
              }}
            >
              <ProjectCardImage
                slug={projects[5].slug}
                url={`/projects/${projects[1].slug}`}
                src={projects[5].thumbnail}
                style={{ flexGrow: 1 }}
              />
              <ProjectCardBody
                url={`/projects/${projects[1].slug}`}
                slug={projects[5].slug}
                title={projects[5].name}
                description={projects[5].description}
                style={{ width: '100%' }}
              >
                <ProjectCardTitle className={'h4'}>
                  {projects[5].name}
                </ProjectCardTitle>
                <ProjectCardDescription lines={6}>
                  {projects[5].description}
                </ProjectCardDescription>
              </ProjectCardBody>
            </Flex>
          </Flex>

          <Flex
            className={s.projectCard}
            style={{
              background: 'white',
              borderRadius: '6px',
              overflow: 'hidden',
              minHeight: '400px',
            }}
          >
            <ProjectCardBody
              url={`/projects/${projects[0].slug}`}
              slug={projects[0].slug}
              title={projects[0].name}
              description={projects[0].description}
            >
              <ProjectCardTitle className={'h3'}>
                {projects[0].name}
              </ProjectCardTitle>
              <ProjectCardDescription lines={6}>
                {projects[1].description}
              </ProjectCardDescription>
            </ProjectCardBody>
            <ProjectCardImage
              slug={projects[0].slug}
              url={`/projects/${projects[0].slug}`}
              src={projects[0].thumbnail}
            />
          </Flex>
          <Flex style={{ gap: '32px' }}>
            <Flex
              style={{
                background: 'white',
                borderRadius: '6px',
                overflow: 'hidden',
                // minHeight: '400px',
                flexGrow: 1,
                flexDirection: 'column',
                width: '40%',
                // maxHeight: '600px',
              }}
            >
              <ProjectCardImage
                slug={projects[5].slug}
                url={`/projects/${projects[1].slug}`}
                src={projects[5].thumbnail}
                style={{ flexGrow: 1 }}
              />
              <ProjectCardBody
                url={`/projects/${projects[1].slug}`}
                slug={projects[5].slug}
                title={projects[5].name}
                description={projects[5].description}
                style={{ width: '100%' }}
              >
                <ProjectCardTitle className={'h4'}>
                  {projects[5].name}
                </ProjectCardTitle>
                <ProjectCardDescription lines={6}>
                  {projects[5].description}
                </ProjectCardDescription>
              </ProjectCardBody>
            </Flex>
            <div style={{ width: '60%' }}>
              <Flex
                style={{
                  background: 'white',
                  borderRadius: '6px',
                  overflow: 'hidden',
                  minHeight: '300px',
                  flexDirection: 'row',
                  maxHeight: '200px',
                  marginBottom: '24px',
                }}
              >
                <ProjectCardImage
                  slug={projects[6].slug}
                  url={`/projects/${projects[6].slug}`}
                  src={projects[6].thumbnail}
                  style={{ minWidth: '300px' }}
                />
                <ProjectCardBody
                  url={`/projects/${projects[6].slug}`}
                  slug={projects[6].slug}
                  title={projects[6].name}
                  // description={projects[6].description}
                  style={{ width: '100%' }}
                >
                  <ProjectCardTitle className={'h4'}>
                    {projects[6].name}
                  </ProjectCardTitle>
                  <ProjectCardDescription>
                    {projects[6].description}
                  </ProjectCardDescription>
                </ProjectCardBody>
              </Flex>
              <Flex
                style={{
                  background: 'white',
                  borderRadius: '6px',
                  overflow: 'hidden',
                  minHeight: '300px',
                  flexDirection: 'row',
                  maxHeight: '200px',
                }}
              >
                <ProjectCardImage
                  slug={projects[4].slug}
                  url={`/projects/${projects[6].slug}`}
                  src={projects[4].thumbnail}
                  style={{ minWidth: '300px' }}
                />
                <ProjectCardBody
                  url={`/projects/${projects[4].slug}`}
                  slug={projects[4].slug}
                  title={projects[4].name}
                  // description={projects[6].description}
                  style={{ width: '100%' }}
                >
                  <ProjectCardTitle className={'h4'}>
                    {projects[4].name}
                  </ProjectCardTitle>
                  <ProjectCardDescription>
                    {projects[4].description}
                  </ProjectCardDescription>
                </ProjectCardBody>
              </Flex>
            </div>
          </Flex>

          {/* {projects.map((project) => (
            <ProjectCard
              key={project.slug}
              slug={project.slug}
              title={project.name}
              description={project.description}
              url={`/projects/${project.slug}`}
              srcThumb={project.thumbnail}
              className={s.projectCard}
            />
          ))} */}
        </div>
      </PageContentWrap>
    </>
  );
};

export default Projects;
