import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';

import PageContentWrap from '../../components/generic/PageContentWrap';
import Nav from '../../components/Nav';
import Button from '../../components/generic/Button';
import Link from 'next/link';
import DevTools from '../../components/DevTools';
import Flex from '../../components/generic/Flex';
import Footer from '../../components/Footer';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import {
  faAws,
  faCss3,
  faGit,
  faGithub,
  faHtml5,
  faJs,
  faJsSquare,
  faNode,
  faNodeJs,
  faReact,
  faShopify,
} from '@fortawesome/free-brands-svg-icons';
import PageWithFooter from '../../components/generic/PageWithFooter';
import Banner from '../../components/Banner';
import ProjectCard from '../../components/ProjectCard';
import ProjectCardWide from '../../components/ProjectCardWide';
import PageTitle from '../../components/PageTitle';
import PageIntro from '../../components/PageIntro';
import projects from '../../data/projects';
import s from './projects.module.css';
import ProjectCardImage from '../../components/ProjectCardImage';
import ProjectCardBody from '../../components/ProjectCardBody';
import ProjectCardTitle from '../../components/ProjectCardTitle';
import ProjectCardDescription from '../../components/ProjectCardDescription';
import ProjectCardTags from '../../components/ProjectCardTags';
import Heading from '../../components/Heading';

const Projects: NextPage = () => {
  const professionalProjects = projects.filter(
    (project) => project.type === 'professional'
  );
  const personalProjects = projects.filter(
    (project) => project.type === 'personal'
  );

  return (
    <>
      <Head>
        <title>Projects | Phillip Miles</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <Banner />
      <PageContentWrap>
        <div style={{ marginBottom: 96 }}>
          <div style={{ textAlign: 'center', marginTop: 64, marginBottom: 96 }}>
            <PageTitle>Projects</PageTitle>
            <PageIntro>
              A sample of projects I have worked on both personally and
              professionally.
            </PageIntro>
          </div>

          {/* <Heading tag="h2" as="h4" style={{ marginBottom: '32px' }}>
            Professional Work
          </Heading> */}
          <ProjectCardWide
            slug={professionalProjects[0].slug}
            url={`/projects/${professionalProjects[0].slug}`}
            title={professionalProjects[0].name}
            description={professionalProjects[0].description}
            descriptionBrief={professionalProjects[0].intro}
            tags={professionalProjects[0].tags}
            thumbnail={professionalProjects[0].thumbnail}
            className={s.projectCardWide}
          />

          <div className={s.grid}>
            {professionalProjects.slice(1).map((project) => (
              <ProjectCard
                key={project.slug}
                slug={project.slug}
                url={`/projects/${project.slug}`}
                title={project.name}
                description={project.intro}
                tags={project.tags}
                thumbnail={project.thumbnail}
                style={{ height: '500px' }}
              />
            ))}
          </div>
          <Heading
            tag="h2"
            as="h4"
            style={{ marginTop: '96px', marginBottom: '32px' }}
          >
            Personal Work
          </Heading>

          <ProjectCardWide
            slug={personalProjects[0].slug}
            url={`/projects/${personalProjects[0].slug}`}
            title={personalProjects[0].name}
            description={personalProjects[0].description}
            tags={personalProjects[0].tags}
            thumbnail={personalProjects[0].thumbnail}
            className={s.projectCardWide}
            descriptionBrief={personalProjects[0].intro}
          />
          <div className={s.grid}>
            {personalProjects.slice(1).map((project) => (
              <ProjectCard
                key={project.slug}
                slug={project.slug}
                url={`/projects/${project.slug}`}
                title={project.name}
                description={project.intro}
                tags={project.tags}
                thumbnail={project.thumbnail}
              />
            ))}
          </div>
        </div>
      </PageContentWrap>
    </>
  );
};

export default Projects;
