import type { NextPage } from 'next';
import Head from 'next/head';
import PageContentWrap from '../../components/generic/PageContentWrap';
import Flex from '../../components/generic/Flex';
import Footer from '../../components/Footer';
import PageWithFooter from '../../components/PageWithFooter';
import Banner from '../../components/Banner';
import PageTitle from '../../components/PageTitle';
import PageIntro from '../../components/PageIntro';
import ToolCard from '../../components/ToolCard';
import tools from '../../data/tools/list';

const Tools: NextPage = () => {
  return (
    <PageWithFooter footerComponent={<Footer />}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main style={{ background: '#ECF4FA' }}>
        <Banner />
        <PageContentWrap>
          <div style={{ marginBottom: 96 }}>
            <div
              style={{ textAlign: 'center', marginTop: 64, marginBottom: 96 }}
            >
              <PageTitle>Tools</PageTitle>
              <PageIntro>
                I write a lot of code. Sometimes I write something useful. Take
                a look. Perhaps you'll find it useful too.
              </PageIntro>
            </div>
            <Flex style={{ justifyContent: 'center' }}>
              <ToolCard
                title="React useFormState hook"
                description="Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean eros velit, sollicitudin vel gravida sit amet, gravida eget sapien."
                srcThumb="/images/react-useFormState-thumb.png"
                href="/tools-useFormState"
              />
              <ToolCard
                title="React Behavioural UI Component Library"
                description="A collection of components that provide behaviours and utilities
                to your visual UI components."
                srcThumb="/images/react-component-library-thumb.png"
                href={`/tools/react-behavioural-ui-component-library/${tools[0].slug}`}
              />
            </Flex>
          </div>
        </PageContentWrap>
      </main>
    </PageWithFooter>
  );
};

export default Tools;
