import type { NextPage } from 'next';
import Head from 'next/head';
import PageContentWrap from '../../../components/generic/PageContentWrap';
import Flex from '../../../components/generic/Flex';
import Footer from '../../../components/Footer';
import PageWithFooter from '../../../components/generic/PageWithFooter';
import Banner from '../../../components/Banner';
import PageTitle from '../../../components/PageTitle';
import PageIntro from '../../../components/PageIntro';
import libraries from '../../../data/tools/functions';
import Link from 'next/link';
import { useRouter } from 'next/router';
import { useEffect, useState } from 'react';
import CodeBox from '../../../components/generic/CodeBox';
import DetachedHoverEffect from '../../../components/generic/DetachedHoverEffect';
import s from './[slug].module.css';
import ContentSlider from '../../../components/generic/ContentSlider';

const ToolsReactLibrary: NextPage = () => {
  const router = useRouter();

  const [currentTool, setCurrentTool] = useState();
  const [currentLibrary, setCurrentLibrary] = useState();

  useEffect(() => {
    const library = libraries.find((tool) => tool.slug === router.query.slug);

    if (!library) {
      return;
    }
    console.log(library.content[0]);
    setCurrentLibrary(library);
    setCurrentTool(library.content[0]);
  }, [router]);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <PageWithFooter>
        <main style={{ background: '#ECF4FA' }}>
          <Banner />
          <PageContentWrap>
            <div style={{ marginBottom: 128 }}>
              <div style={{ textAlign: 'center', marginTop: 64 }}>
                <PageTitle>Handy Dandy Functions</PageTitle>
                <PageIntro>
                  React Construct is a library of low-level react components
                  used by developers to construct their own UI components.
                  react-construct-components
                </PageIntro>
              </div>
            </div>
          </PageContentWrap>
          <div
            style={{
              background: 'white',
              //padding: '16px'
              paddingTop: '64px',
              position: 'sticky',
              top: 0,
            }}
          >
            <PageContentWrap>
              <Flex
                style={{
                  //gap: '64px',
                  width: '100%',
                }}
              >
                <div
                  style={{
                    width: '30%',
                    paddingRight: '64px',
                    flexShrink: 0,
                    flexGrow: 0,
                  }}
                >
                  {libraries.map((library) => (
                    <Link
                      key={library.slug}
                      href={library.slug}
                      scroll={false}
                      passHref={true}
                      style={{
                        margin: '24px',
                      }}
                    >
                      <DetachedHoverEffect
                        className={`${s.hover} ${
                          currentLibrary &&
                          library.slug === currentLibrary.slug &&
                          s.hoverSelect
                        }`}
                      >
                        <span
                          style={{
                            display: 'block',
                            paddingLeft: '16px',
                            paddingRight: '16px',
                            paddingTop: '8px',
                            paddingBottom: '8px',
                          }}
                        >
                          {library.title}
                        </span>
                      </DetachedHoverEffect>
                    </Link>
                  ))}
                </div>
                <div style={{ marginBottom: 96, width: '70%' }}>
                  <p
                    style={{
                      maxWidth: 700,
                      marginLeft: 'auto',
                      marginRight: 'auto',
                      marginTop: '48px',
                      marginBottom: '48px',
                    }}
                  >
                    {currentTool
                      ? currentTool.description
                      : 'Function not found.'}
                  </p>

                  {currentTool &&
                    currentTool.content.map((example, index) => (
                      <>
                        <div
                          style={{
                            // marginLeft: 8,
                            // width: '100%',
                            border: '2px solid #262C35',
                            borderRadius: '6px 6px 0px 0',
                            // padding: '16px',
                            flexGrow: 0,
                            flexShrink: 0,
                            background: '#ecf4fa',
                            padding: '24px',
                          }}
                        >
                          <example.example />
                        </div>
                        <div style={{}}>
                          {example.exampleMarkDown && (
                            <CodeBox
                              code={example.exampleMarkDown}
                              style={{
                                height: '100%',
                                borderRadius: '0px 0 6px 6px',
                                marginBottom: '64px',
                              }}
                            />
                          )}
                        </div>
                      </>
                    ))}
                </div>
              </Flex>
            </PageContentWrap>
          </div>
        </main>
        <Footer />
      </PageWithFooter>
    </>
  );
};

export default ToolsReactLibrary;
