import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';

import Hero from '../components/Hero';
import Projects from '../components/Projects';
import PageContentWrap from '../components/generic/PageContentWrap';
import Nav from '../components/Nav';
import Button from '../components/generic/Button';
import Link from 'next/link';
import DevTools from '../components/DevTools';
import Flex from '../components/generic/Flex';
import Footer from '../components/Footer';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import {
  faAws,
  faCss3,
  faGit,
  faGithub,
  faHtml5,
  faJs,
  faJsSquare,
  faNode,
  faNodeJs,
  faReact,
  faShopify,
} from '@fortawesome/free-brands-svg-icons';
import PageWithFooter from '../components/PageWithFooter';
import Banner from '../components/Banner';
import ContentSlider from '../components/generic/ContentSlider';

const Home: NextPage = () => {
  return (
    <PageWithFooter footerComponent={<Footer />}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className={styles.introBlock}>
          <Banner invert />

          <header className={styles.header}>
            <div className={styles.headerLeft}>
              <h1 className={styles.title}>Websites that connect people</h1>
              <p className={styles.description}>
                React front-end web developer
              </p>
              <div className={styles.ctaWrap}>
                <Link href="/" className={styles.cta}>
                  Get in touch
                </Link>
                <div className={styles.ctaShadow} />
              </div>
            </div>
            <div className={styles.headerRight}>
              <Hero />
            </div>
          </header>
        </div>
        <div style={{ backgroundColor: '#ECF4FA', width: '100%' }}>
          <PageContentWrap>
            <Flex
              style={{
                paddingTop: 92,
                paddingBottom: 24,
                opacity: 0.9,
                justifyContent: 'center',
              }}
            >
              <div
                style={{
                  display: 'block',
                  height: 32,
                  width: 32,
                  marginRight: 24,
                }}
              >
                <FontAwesomeIcon icon={faReact} />
              </div>

              <div
                style={{
                  display: 'block',
                  height: 32,
                  width: 32,
                  marginRight: 24,
                }}
              >
                <FontAwesomeIcon icon={faNodeJs} />
              </div>
              <div
                style={{
                  display: 'block',
                  height: 32,
                  width: 32,
                }}
              >
                <FontAwesomeIcon icon={faGit} />
              </div>
            </Flex>
            <Projects />
            <DevTools />
          </PageContentWrap>
        </div>
        <div
          style={{
            backgroundColor: '#007BE4',
            width: '100%',
            paddingTop: 80,
            paddingBottom: 80,
          }}
        >
          <div style={{ maxWidth: 900, margin: 'auto' }}>
            {/* <p style={{ textAlign: 'center', color: 'white', fontSize: 20 }}>
              Worked with
            </p> */}
            <Flex style={{ justifyContent: 'center', alignItems: 'center' }}>
              <Image
                src={'/images/companies/logo_anz_h_white.svg'}
                width={140}
                height={100}
                alt="ANZ Logo"
                style={{ margin: 24 }}
              />
              <Image
                src={'/images/companies/logo_coles_white.svg'}
                width={140}
                height={100}
                alt="Coles Logo"
                style={{ margin: 24 }}
              />
              <Image
                src={'/images/companies/logo_deakinuni_h_white.svg'}
                width={140}
                height={100}
                alt="Deakin University Logo"
                style={{ margin: 24 }}
              />

              <Image
                src={'/images/companies/logo_auspost_white.svg'}
                width={140}
                height={100}
                alt="Aus Post Logo"
                style={{ margin: 24 }}
              />
            </Flex>
            <Flex style={{ justifyContent: 'center', alignItems: 'center' }}>
              <Image
                src={'/images/companies/logo_hla_white.svg'}
                width={140}
                height={100}
                alt="HLA Logo"
                style={{ margin: 24 }}
              />
              <Image
                src={'/images/companies/logo_cpa_white.svg'}
                width={140}
                height={100}
                alt="CPA Logo"
                style={{ margin: 24 }}
              />
              <Image
                src={'/images/companies/logo_transurban_white.svg'}
                width={140}
                height={100}
                alt="Transurban Logo"
                style={{ margin: 24 }}
              />
              <Image
                src={'/images/companies/logo_dhhs_white.png'}
                width={140}
                height={50}
                alt="DHHS Logo"
                style={{ margin: 24 }}
              />
            </Flex>
          </div>
        </div>
      </main>
    </PageWithFooter>
  );
};

export default Home;
