import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <header className={styles.header}>
          <div className={styles.headerLeft}>
            <h1 className={styles.title}>Websites that connect people</h1>
            <p className={styles.description}>React front-end web developer</p>
            <a href="" className={styles.cta}>
              Get in touch
            </a>
          </div>
          <div className={styles.headerRight}>
            <video
              controls
              autoPlay
              loop
              muted
              playsInline
              style={{
                pointerEvents: 'none',
                width: '500px',
                height: '400px',
                objectFit: 'cover',
                borderRadius: '16px',
              }}
            >
              <source src="/clients.mp4" type="video/mp4" />
            </video>
            {/* <iframe
              frameBorder={0}
              width="420"
              height="315"
              src={`https://www.youtube.com/embed/tgbNymZ7vqY?autoplay=1&mute=1&controls=0&disablekb=1&loop=1&modestbranding=0&showinfo=0&rel=0`}
            ></iframe> */}
          </div>
        </header>

        <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Learn &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/canary/examples"
            className={styles.card}
          >
            <h2>Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
          >
            <h2>Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
};

export default Home;
