import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';
import PageContentWrap from '../components/generic/PageContentWrap';
import Nav from '../components/Nav';
import Button from '../components/generic/Button';
import Link from 'next/link';
import DevTools from '../components/DevTools';
import Flex from '../components/generic/Flex';
import Footer from '../components/Footer';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import {
  faAws,
  faCss3,
  faGit,
  faGithub,
  faHtml5,
  faJs,
  faJsSquare,
  faNode,
  faNodeJs,
  faReact,
  faShopify,
} from '@fortawesome/free-brands-svg-icons';
import PageWithFooter from '../components/PageWithFooter';
import Banner from '../components/Banner';
import ProjectCard from '../components/ProjectCard';
import PageTitle from '../components/PageTitle';
import PageIntro from '../components/PageIntro';

const Projects: NextPage = () => {
  return (
    <PageWithFooter footerComponent={<Footer />}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main style={{ background: '#ECF4FA' }}>
        <Banner />
        <PageContentWrap>
          <div style={{ marginBottom: 96 }}>
            <div
              style={{ textAlign: 'center', marginTop: 64, marginBottom: 96 }}
            >
              <PageTitle>Projects</PageTitle>
              <PageIntro>Useful things I have made for developers.</PageIntro>
            </div>
            <ProjectCard
              title="Woodfort Cases"
              description={
                'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean eros velit, sollicitudin vel gravida sit amet, gravida eget sapien. Proin tellus lorem, rhoncus eu pharetra non, dapibus a nisl. Fusce aliquam nisi ut nunc suscipit sollicitudin.'
              }
              url="/"
              srcThumb="/images/woodfort_walnut.jpeg"
              style={{ marginBottom: 64 }}
            />
            <ProjectCard
              title="Verso Learning App"
              description={
                'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean eros velit, sollicitudin vel gravida sit amet, gravida eget sapien. Proin tellus lorem, rhoncus eu pharetra non, dapibus a nisl. Fusce aliquam nisi ut nunc suscipit sollicitudin.'
              }
              url="/"
              srcThumb="/images/versohome.png"
              style={{ marginBottom: 64 }}
            />
            <ProjectCard
              title="Thought Stream Mobile App"
              description={
                'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean eros velit, sollicitudin vel gravida sit amet, gravida eget sapien. Proin tellus lorem, rhoncus eu pharetra non, dapibus a nisl. Fusce aliquam nisi ut nunc suscipit sollicitudin.'
              }
              url="/"
              srcThumb="/projects-thumb.png"
              style={{ marginBottom: 64 }}
            />
            <ProjectCard
              title="Test"
              description={
                'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean eros velit, sollicitudin vel gravida sit amet, gravida eget sapien. Proin tellus lorem, rhoncus eu pharetra non, dapibus a nisl. Fusce aliquam nisi ut nunc suscipit sollicitudin.'
              }
              url="/"
              srcThumb="/images/cpa_screen_ipad.jpeg"
              style={{ marginBottom: 64 }}
            />
            <ProjectCard
              title="Test"
              description={
                'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean eros velit, sollicitudin vel gravida sit amet, gravida eget sapien. Proin tellus lorem, rhoncus eu pharetra non, dapibus a nisl. Fusce aliquam nisi ut nunc suscipit sollicitudin.'
              }
              url="/"
              srcThumb="/images/gametalk_composite.jpeg"
              style={{ marginBottom: 64 }}
            />
          </div>
        </PageContentWrap>
      </main>
    </PageWithFooter>
  );
};

export default Projects;
