import type { NextPage } from 'next';
import Head from 'next/head';
import PageContentWrap from '../components/generic/PageContentWrap';
import Flex from '../components/generic/Flex';
import Footer from '../components/Footer';
import PageWithFooter from '../components/PageWithFooter';
import Banner from '../components/Banner';
import PageTitle from '../components/PageTitle';
import PageIntro from '../components/PageIntro';
import tools from '../data/tools/list';
import RenderMarkdown from '../components/generic/RenderMarkdown';
import { useEffect, useState } from 'react';
import { renderToStaticMarkup, renderToString } from 'react-dom/server';
import Test from '../data/tools/test';
import reactElementToJSXString from 'react-element-to-jsx-string';

const ToolsReactLibrary: NextPage = () => {
  // const firstLineIndex = tools[0].content.content.indexOf('\n');
  // const lastLineIndex = tools[0].content.content.lastIndexOf('\n');
  // const boop = tools[0].content.content.slice(
  //   firstLineIndex + 1,
  //   lastLineIndex - 4
  // );
  // console.log(boop);
  // console.log(renderToStaticMarkup(boop));
  const Example = tools[0].content.example;
  const markdown = tools[0].content.exampleMarkDown;

  return (
    <PageWithFooter footerComponent={<Footer />}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main style={{ background: '#ECF4FA' }}>
        <Banner />
        <PageContentWrap>
          <div style={{ marginBottom: 96 }}>
            <div
              style={{ textAlign: 'center', marginTop: 64, marginBottom: 96 }}
            >
              <PageTitle>React Functional UI Component Library</PageTitle>
              <PageIntro>{tools[0].description}</PageIntro>
            </div>
          </div>
          <div>
            <Flex>
              <div style={{ width: '50%' }}>
                {/* <RenderMarkdown content={tools[0].content.content} /> */}
                {/* <RenderMarkdown content={`${renderToString(<Test />)}`} /> */}
                <RenderMarkdown content={markdown} />

                {/* <RenderMarkdown
                  content="```jsx
                  <Flex
                    style={{ width: '100%', justifyContent: 'space-between' }}
                  >
                    <div>Hi</div>
                    <div>Hi 2</div> <div>Hi 3</div>
                  </Flex>
                  ```"
                /> */}
              </div>
              <div style={{ width: '50%', border: '1px solid black' }}>
                <Flex>
                  <Example />
                  {/* <Flex
                    style={{ width: '100%', justifyContent: 'space-between' }}
                  > */}
                  {/* <div>Hi</div>
                    <div>Hi 2</div>
                    <div>Hi 3</div> */}
                  {/* <Boop /> */}
                  {/* <div
                    style={{ width: '100%' }}
                    dangerouslySetInnerHTML={{
                      __html: renderToStaticMarkup(boop),
                    }}
                  ></div> */}

                  {/* <Test /> */}
                  {/* </Flex> */}
                </Flex>
              </div>
            </Flex>
          </div>
        </PageContentWrap>
      </main>
    </PageWithFooter>
  );
};

export default ToolsReactLibrary;
