import type { NextPage } from 'next';
import Head from 'next/head';
import PageContentWrap from '../components/generic/PageContentWrap';
import Flex from '../components/generic/Flex';
import Footer from '../components/Footer';
import PageWithFooter from '../components/PageWithFooter';
import Banner from '../components/Banner';
import PageTitle from '../components/PageTitle';
import PageIntro from '../components/PageIntro';
import tools from '../data/tools/list';
import RenderMarkdown from '../components/generic/RenderMarkdown';
import { useEffect, useState } from 'react';

const ToolsReactLibrary: NextPage = () => {
  return (
    <PageWithFooter footerComponent={<Footer />}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main style={{ background: '#ECF4FA' }}>
        <Banner />
        <PageContentWrap>
          <div style={{ marginBottom: 96 }}>
            <div
              style={{ textAlign: 'center', marginTop: 64, marginBottom: 96 }}
            >
              <PageTitle>React Functional UI Component Library</PageTitle>
              <PageIntro>
                I write a lot of code. Sometimes I write something useful. Take
                a look. Perhaps you'll find it useful too.
              </PageIntro>
            </div>
          </div>
          <div>
            <Flex>
              <div style={{ width: '50%' }}>
                <RenderMarkdown content={tools[0].content.content} />

                {/* {`
import React from 'react';

const ToolsReactLibrary = ({children}) => {
  return (
    <PageWithFooter>
      <Head>
        {children}
      </Head>
    </PageWithFooter>
  )
};`} */}
              </div>
              <div style={{ width: '50%', border: '1px solid black' }}>
                <Flex>derp</Flex>
              </div>
            </Flex>
          </div>
        </PageContentWrap>
      </main>
    </PageWithFooter>
  );
};

export default ToolsReactLibrary;
