import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';
import PageContentWrap from '../components/generic/PageContentWrap';
import Nav from '../components/Nav';
import Button from '../components/generic/Button';
import Link from 'next/link';
import DevTools from '../components/DevTools';
import Flex from '../components/generic/Flex';
import Footer from '../components/Footer';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import {
  faAws,
  faCss3,
  faGit,
  faGithub,
  faHtml5,
  faJs,
  faJsSquare,
  faNode,
  faNodeJs,
  faReact,
  faShopify,
} from '@fortawesome/free-brands-svg-icons';
import PageWithFooter from '../components/PageWithFooter';
import Banner from '../components/Banner';
import ProjectCard from '../components/ProjectCard';
import PageTitle from '../components/PageTitle';
import PageIntro from '../components/PageIntro';
import ToolCard from '../components/ToolCard';

const Tools: NextPage = () => {
  return (
    <PageWithFooter footerComponent={<Footer />}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main style={{ background: '#ECF4FA' }}>
        <Banner />
        <PageContentWrap>
          <div style={{ marginBottom: 96 }}>
            <div
              style={{ textAlign: 'center', marginTop: 64, marginBottom: 96 }}
            >
              <PageTitle>Tools</PageTitle>
              <PageIntro>
                I write a lot of code. Sometimes I write something useful. Take
                a look. Perhaps you'll find it useful too.
              </PageIntro>
            </div>
            <Flex style={{ justifyContent: 'center' }}>
              <ToolCard
                title="React useFormState hook"
                description="Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean eros velit, sollicitudin vel gravida sit amet, gravida eget sapien."
                srcThumb="/images/react-useFormState-thumb.png"
                href="/tools-useFormState"
              />
              <ToolCard
                title="React Functional UI Component Library"
                description="Proin tellus lorem, rhoncus eu pharetra non, dapibus a nisl. Fusce aliquam nisi ut nunc suscipit sollicitudin."
                srcThumb="/images/react-component-library-thumb.png"
                href="/tools-react-library"
              />
            </Flex>
          </div>
        </PageContentWrap>
      </main>
    </PageWithFooter>
  );
};

export default Tools;
