import type { NextPage } from 'next';
import Head from 'next/head';
import PageContentWrap from '../../components/generic/PageContentWrap';
import Flex from '../../components/generic/Flex';
import Footer from '../../components/Footer';
import PageWithFooter from '../../components/generic/PageWithFooter';
import Banner from '../../components/Banner';
import PageTitle from '../../components/PageTitle';
import PageIntro from '../../components/PageIntro';
import ToolCard from '../../components/ToolCard';
import tools from '../../data/tools/list';
import functions from '../../data/tools/functions';
import s from './index.module.css';

const Tools: NextPage = () => {
  return (
    <>
      <Head>
        <title>Resources | Phillip Miles React Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Banner />
      <PageContentWrap>
        <div style={{ marginBottom: 96 }}>
          <div style={{ textAlign: 'center', marginTop: 64, marginBottom: 96 }}>
            <PageTitle>Resources</PageTitle>
            <PageIntro>
              I write a lot of code. Sometimes I write something useful. Take a
              look. Perhaps you&apos;ll find it useful too.
            </PageIntro>
          </div>
          <Flex className={s.tools}>
            <ToolCard
              className={s.tool}
              title="React Construct"
              description="React Construct is a library of low-level react components used to construct reusable UI components."
              srcThumb="/images/react-component-library-thumb.png"
              href={`/resources/react-construct/${tools[0].slug}/${tools[0].items[0].slug}`}
            />
            <ToolCard
              className={s.tool}
              title="React UseFormState"
              description="UseFormState is a flexible React Hook that manages the state of a web form."
              srcThumb="/images/react-useFormState-thumb.png"
              href="/resources/use-form-state"
            />
            <ToolCard
              className={s.tool}
              title="Handy Dandy Functions"
              description="Handy Dandy Functions are a collection of simple Javascript functions that I have found myself using in many projects."
              srcThumb="/images/react-component-library-thumb.png"
              href={`/resources/handy-dandy-functions/${functions[0].slug}`}
            />
          </Flex>
        </div>
      </PageContentWrap>
    </>
  );
};

export default Tools;
